### PR TITLE
Update lz-string.js

### PR DESCRIPTION
**Pull request by darrylyeo**
Version 1.5.0, perhaps?
* Made code _much_ more compact and reusable (reduced **501** lines of code to **273**)!
* Defined some reusable functions within `_compress()` (perhaps you can come up with better names).

### CODE REVIEW

**Comment by pieroxy** [comment]
If you look at LZ-String history, in inlined all the functions on purpose to make it faster... I know it made the code awful and bigger, but the performance was greatly increased.

Ca you do a jsperf to compare it to the current version ?

**Comment by darrylyeo** [comment]
Okay, I moved the three helper functions to outside `_compress()` so as to not redefine them each time. It comes out to be a little slower.
http://jsperf.com/lzstring-test

**Comment by pieroxy** [comment]
Well, it doesn't look good. Am I willing to trade a few lines vs 20% slower compression? Well, not really... 

On another note, I couldn't test on internet explorer for some reason...

**Comment by darrylyeo** [comment]
I see what you mean.

**Pull request closed without merging**
