### PR TITLE
Chore: Updating Dependencies

### PR DESCRIPTION
**Pull request by karnthis**
This PR combines Dependabot PRs #244 #260 #261 #263 #264 and #265 and includes some additional audit fixes Dependabot missed. Build succeeded, Tests pass.

Please update the Dependabot settings so I stop getting roughly 30 emails from this project every Monday evening.

### CODE REVIEW

**Comment by karnthis** [comment]
bump for @Rycochet to see

**Comment by Rycochet** [comment]
I'm just back from 2 weeks of busy - will approve this, but if you have the time (before I do) - there's a code as config that can tell it to update things as groups of updates together - like testing, linting, building etc - it's on my TODO list and I'll try to have a look next week if you don't

**Review by Rycochet — APPROVED** [review]

**Comment by karnthis** [comment]
> I'm just back from 2 weeks of busy - will approve this, but if you have the time (before I do) - there's a code as config that can tell it to update things as groups of updates together - like testing, linting, building etc - it's on my TODO list and I'll try to have a look next week if you don't

Sorry not sure what you're referring to. Can you elaborate?

**Comment by Rycochet** [comment]
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups - hopefully that page makes things more clear - it should be able to cut down the number of PRs generated 😄

**Pull request merged**
